apiVersion: v1
kind: ConfigMap
metadata:
  name: firstpay-config
  namespace: {{ .Values.global.namespace }}
  labels:
    app.kubernetes.io/part-of: firstpay-studio
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  SPRING_PROFILES_ACTIVE: {{ .Values.common.springProfile | quote }}
  TRACING_SAMPLE_RATE: {{ .Values.common.tracingSampleRate | quote }}
  OTEL_EXPORTER_OTLP_ENDPOINT: {{ .Values.common.otlpEndpoint | quote }}
  {{- range $k, $v := .Values.common.config }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
{{- if .Values.secrets.create }}
---
apiVersion: v1
kind: Secret
metadata:
  name: firstpay-secrets
  namespace: {{ .Values.global.namespace }}
  labels:
    app.kubernetes.io/part-of: firstpay-studio
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
stringData:
  {{- range $k, $v := .Values.secrets.data }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
{{- end }}
